apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: image-registry-pvc
    namespace: openshift-image-registry
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 300Gi
    storageClassName: managed-nfs-storage